spring.application.name=CropPing

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

spring.h2.console.enabled=true
spring.h2.console.path=/h2

line.channel.token=n6aoNR6l5Y5+rJRLpv1hWb5p/D7uUZEVYVaUcB3T3E4fZNGvhrv5MPmcQ3yuAQppJjeJnTgrIjkiRP4rXCbkpWpdoTB61x8Ub8U9f4VkNoyBVcaXTM4mktyr10774MyJcuewdRrQDkk9++Gmblmo1AdB04t89/1O/w1cDnyilFU=
line.channel.secret=839445964f00afffcfea3b4ab07f1eac